kind: network_interface_application_security_group_association
azureType: azurerm_network_interface_application_security_group_association
abbr: niasga
module: Modules/Network/networkInterfaceAsgAssociation
stack: Network
category: Network
noName: true
required: [network_interface_id, application_security_group_id]
optional: []
args: {}
sockets:
  - name: network_interface_id
    kind: network_interface
    required: true
  - name: application_security_group_id
    kind: application_security_group
    required: true
blocks: []
